CREATE EXTENSION "citext";

CREATE TABLE users
(
    user_id             SERIAL      NOT NULL PRIMARY KEY,
    first_name          TEXT        DEFAULT NULL,
    last_name           TEXT        DEFAULT NULL,
    height              NUMERIC     DEFAULT NULL,
    weight              NUMERIC     DEFAULT NULL,
    sex                 CHAR(1)     DEFAULT NULL,
    dob                 DATE        DEFAULT NULL,
    email               CITEXT      NOT NULL UNIQUE,
    password            TEXT        NOT NULL,
    -- Diabetes specifics
    diabetes_type       INTEGER     DEFAULT NULL,
    high_blood_pressure BOOLEAN     DEFAULT NULL,
    pregnant            BOOLEAN     DEFAULT NULL,
    insulin_tdd         INTEGER     DEFAULT NULL,
    background_dose     INTEGER     DEFAULT NULL,
    pre_meal_target	NUMERIC     DEFAULT NULL,
    post_meal_target	NUMERIC     DEFAULT NULL,
    basal_corr_factor   NUMERIC     DEFAULT NULL,
    bolus_corr_factor   NUMERIC     DEFAULT NULL,
    grams_carb_per_unit NUMERIC     DEFAULT NULL
);

CREATE UNIQUE INDEX ON users(email);


CREATE TABLE readings
(
    reading_id          SERIAL      NOT NULL PRIMARY KEY,
    user_id             INTEGER     REFERENCES users(user_id) NOT NULL,
    reading_timestamp   TIMESTAMP   WITH TIME ZONE DEFAULT (now() AT TIME ZONE 'EST') NOT NULL,
    reading             NUMERIC     NOT NULL
);


CREATE TABLE doses
(
    dose_id             SERIAL      NOT NULL PRIMARY KEY,
    user_id             INTEGER     REFERENCES users(user_id) NOT NULL,
    dose_timestamp      TIMESTAMP   WITH TIME ZONE DEFAULT (now() AT TIME ZONE 'EST') NOT NULL,
    dose_units          INTEGER     NOT NULL
);


CREATE TABLE foods
(
    food_id SERIAL NOT NULL PRIMARY KEY,
    code TEXT DEFAULT NULL,
    url TEXT DEFAULT NULL,
    creator TEXT DEFAULT NULL,
    created_t TEXT DEFAULT NULL,
    created_datetime TEXT DEFAULT NULL,
    last_modified_t TEXT DEFAULT NULL,
    last_modified_datetime TEXT DEFAULT NULL,
    product_name TEXT DEFAULT NULL,
    generic_name TEXT DEFAULT NULL,
    quantity TEXT DEFAULT NULL,
    packaging TEXT DEFAULT NULL,
    packaging_tags TEXT DEFAULT NULL,
    brands TEXT DEFAULT NULL,
    brands_tags TEXT DEFAULT NULL,
    categories TEXT DEFAULT NULL,
    categories_tags TEXT DEFAULT NULL,
    categories_en TEXT DEFAULT NULL,
    origins TEXT DEFAULT NULL,
    origins_tags TEXT DEFAULT NULL,
    manufacturing_places TEXT DEFAULT NULL,
    manufacturing_places_tags TEXT DEFAULT NULL,
    labels TEXT DEFAULT NULL,
    labels_tags TEXT DEFAULT NULL,
    labels_en TEXT DEFAULT NULL,
    emb_codes TEXT DEFAULT NULL,
    emb_codes_tags TEXT DEFAULT NULL,
    first_packaging_code_geo TEXT DEFAULT NULL,
    cities TEXT DEFAULT NULL,
    cities_tags TEXT DEFAULT NULL,
    purchase_places TEXT DEFAULT NULL,
    stores TEXT DEFAULT NULL,
    countries TEXT DEFAULT NULL,
    countries_tags TEXT DEFAULT NULL,
    countries_en TEXT DEFAULT NULL,
    ingredients_text TEXT DEFAULT NULL,
    allergens TEXT DEFAULT NULL,
    allergens_en TEXT DEFAULT NULL,
    traces TEXT DEFAULT NULL,
    traces_tags TEXT DEFAULT NULL,
    traces_en TEXT DEFAULT NULL,
    serving_size TEXT DEFAULT NULL,
    no_nutriments NUMERIC DEFAULT NULL,
    additives_n NUMERIC DEFAULT NULL,
    additives TEXT DEFAULT NULL,
    additives_tags TEXT DEFAULT NULL,
    additives_en TEXT DEFAULT NULL,
    ingredients_from_palm_oil_n NUMERIC DEFAULT NULL,
    ingredients_from_palm_oil NUMERIC DEFAULT NULL,
    ingredients_from_palm_oil_tags TEXT DEFAULT NULL,
    ingredients_that_may_be_from_palm_oil_n NUMERIC DEFAULT NULL,
    ingredients_that_may_be_from_palm_oil NUMERIC DEFAULT NULL,
    ingredients_that_may_be_from_palm_oil_tags TEXT DEFAULT NULL,
    nutrition_grade_uk NUMERIC DEFAULT NULL,
    nutrition_grade_fr TEXT DEFAULT NULL,
    pnns_groups_1 TEXT DEFAULT NULL,
    pnns_groups_2 TEXT DEFAULT NULL,
    states TEXT DEFAULT NULL,
    states_tags TEXT DEFAULT NULL,
    states_en TEXT DEFAULT NULL,
    main_category TEXT DEFAULT NULL,
    main_category_en TEXT DEFAULT NULL,
    image_url TEXT DEFAULT NULL,
    image_small_url TEXT DEFAULT NULL,
    energy_100g NUMERIC DEFAULT NULL,
    energy_from_fat_100g NUMERIC DEFAULT NULL,
    fat_100g NUMERIC DEFAULT NULL,
    saturated_fat_100g NUMERIC DEFAULT NULL,
    butyric_acid_100g NUMERIC DEFAULT NULL,
    caproic_acid_100g NUMERIC DEFAULT NULL,
    caprylic_acid_100g NUMERIC DEFAULT NULL,
    capric_acid_100g NUMERIC DEFAULT NULL,
    lauric_acid_100g NUMERIC DEFAULT NULL,
    myristic_acid_100g NUMERIC DEFAULT NULL,
    palmitic_acid_100g NUMERIC DEFAULT NULL,
    stearic_acid_100g NUMERIC DEFAULT NULL,
    arachidic_acid_100g NUMERIC DEFAULT NULL,
    behenic_acid_100g NUMERIC DEFAULT NULL,
    lignoceric_acid_100g NUMERIC DEFAULT NULL,
    cerotic_acid_100g NUMERIC DEFAULT NULL,
    montanic_acid_100g NUMERIC DEFAULT NULL,
    melissic_acid_100g NUMERIC DEFAULT NULL,
    monounsaturated_fat_100g NUMERIC DEFAULT NULL,
    polyunsaturated_fat_100g NUMERIC DEFAULT NULL,
    omega_3_fat_100g NUMERIC DEFAULT NULL,
    alpha_linolenic_acid_100g NUMERIC DEFAULT NULL,
    eicosapentaenoic_acid_100g NUMERIC DEFAULT NULL,
    docosahexaenoic_acid_100g NUMERIC DEFAULT NULL,
    omega_6_fat_100g NUMERIC DEFAULT NULL,
    linoleic_acid_100g NUMERIC DEFAULT NULL,
    arachidonic_acid_100g NUMERIC DEFAULT NULL,
    gamma_linolenic_acid_100g NUMERIC DEFAULT NULL,
    dihomo_gamma_linolenic_acid_100g NUMERIC DEFAULT NULL,
    omega_9_fat_100g NUMERIC DEFAULT NULL,
    oleic_acid_100g NUMERIC DEFAULT NULL,
    elaidic_acid_100g NUMERIC DEFAULT NULL,
    gondoic_acid_100g NUMERIC DEFAULT NULL,
    mead_acid_100g NUMERIC DEFAULT NULL,
    erucic_acid_100g NUMERIC DEFAULT NULL,
    nervonic_acid_100g NUMERIC DEFAULT NULL,
    trans_fat_100g NUMERIC DEFAULT NULL,
    cholesterol_100g NUMERIC DEFAULT NULL,
    carbohydrates_100g NUMERIC DEFAULT NULL,
    sugars_100g NUMERIC DEFAULT NULL,
    sucrose_100g NUMERIC DEFAULT NULL,
    glucose_100g NUMERIC DEFAULT NULL,
    fructose_100g NUMERIC DEFAULT NULL,
    lactose_100g NUMERIC DEFAULT NULL,
    maltose_100g NUMERIC DEFAULT NULL,
    maltodextrins_100g NUMERIC DEFAULT NULL,
    starch_100g NUMERIC DEFAULT NULL,
    polyols_100g NUMERIC DEFAULT NULL,
    fiber_100g NUMERIC DEFAULT NULL,
    proteins_100g NUMERIC DEFAULT NULL,
    casein_100g NUMERIC DEFAULT NULL,
    serum_proteins_100g NUMERIC DEFAULT NULL,
    nucleotides_100g NUMERIC DEFAULT NULL,
    salt_100g NUMERIC DEFAULT NULL,
    sodium_100g NUMERIC DEFAULT NULL,
    alcohol_100g NUMERIC DEFAULT NULL,
    vitamin_a_100g NUMERIC DEFAULT NULL,
    beta_carotene_100g NUMERIC DEFAULT NULL,
    vitamin_d_100g NUMERIC DEFAULT NULL,
    vitamin_e_100g NUMERIC DEFAULT NULL,
    vitamin_k_100g NUMERIC DEFAULT NULL,
    vitamin_c_100g NUMERIC DEFAULT NULL,
    vitamin_b1_100g NUMERIC DEFAULT NULL,
    vitamin_b2_100g NUMERIC DEFAULT NULL,
    vitamin_pp_100g NUMERIC DEFAULT NULL,
    vitamin_b6_100g NUMERIC DEFAULT NULL,
    vitamin_b9_100g NUMERIC DEFAULT NULL,
    vitamin_b12_100g NUMERIC DEFAULT NULL,
    biotin_100g NUMERIC DEFAULT NULL,
    pantothenic_acid_100g NUMERIC DEFAULT NULL,
    silica_100g NUMERIC DEFAULT NULL,
    bicarbonate_100g NUMERIC DEFAULT NULL,
    potassium_100g NUMERIC DEFAULT NULL,
    chloride_100g NUMERIC DEFAULT NULL,
    calcium_100g NUMERIC DEFAULT NULL,
    phosphorus_100g NUMERIC DEFAULT NULL,
    iron_100g NUMERIC DEFAULT NULL,
    magnesium_100g NUMERIC DEFAULT NULL,
    zinc_100g NUMERIC DEFAULT NULL,
    copper_100g NUMERIC DEFAULT NULL,
    manganese_100g NUMERIC DEFAULT NULL,
    fluoride_100g NUMERIC DEFAULT NULL,
    selenium_100g NUMERIC DEFAULT NULL,
    chromium_100g NUMERIC DEFAULT NULL,
    molybdenum_100g NUMERIC DEFAULT NULL,
    iodine_100g NUMERIC DEFAULT NULL,
    caffeine_100g NUMERIC DEFAULT NULL,
    taurine_100g NUMERIC DEFAULT NULL,
    ph_100g NUMERIC DEFAULT NULL,
    fruits_vegetables_nuts_100g NUMERIC DEFAULT NULL,
    collagen_meat_protein_ratio_100g NUMERIC DEFAULT NULL,
    cocoa_100g NUMERIC DEFAULT NULL,
    chlorophyl_100g NUMERIC DEFAULT NULL,
    carbon_footprint_100g NUMERIC DEFAULT NULL,
    nutrition_score_fr_100g NUMERIC DEFAULT NULL,
    nutrition_score_uk_100g NUMERIC DEFAULT NULL
);

INSERT INTO foods
(
    code,
    url,
    creator,
    created_t,
    created_datetime,
    last_modified_t,
    last_modified_datetime,
    product_name,
    generic_name,
    quantity,
    packaging,
    packaging_tags,
    brands,
    brands_tags,
    categories,
    categories_tags,
    categories_en,
    origins,
    origins_tags,
    manufacturing_places,
    manufacturing_places_tags,
    labels,
    labels_tags,
    labels_en,
    emb_codes,
    emb_codes_tags,
    first_packaging_code_geo,
    cities,
    cities_tags,
    purchase_places,
    stores,
    countries,
    countries_tags,
    countries_en,
    ingredients_text,
    allergens,
    allergens_en,
    traces,
    traces_tags,
    traces_en,
    serving_size,
    no_nutriments,
    additives_n,
    additives,
    additives_tags,
    additives_en,
    ingredients_from_palm_oil_n,
    ingredients_from_palm_oil,
    ingredients_from_palm_oil_tags,
    ingredients_that_may_be_from_palm_oil_n,
    ingredients_that_may_be_from_palm_oil,
    ingredients_that_may_be_from_palm_oil_tags,
    nutrition_grade_uk,
    nutrition_grade_fr,
    pnns_groups_1,
    pnns_groups_2,
    states,
    states_tags,
    states_en,
    main_category,
    main_category_en,
    image_url,
    image_small_url,
    energy_100g,
    energy_from_fat_100g,
    fat_100g,
    saturated_fat_100g,
    butyric_acid_100g,
    caproic_acid_100g,
    caprylic_acid_100g,
    capric_acid_100g,
    lauric_acid_100g,
    myristic_acid_100g,
    palmitic_acid_100g,
    stearic_acid_100g,
    arachidic_acid_100g,
    behenic_acid_100g,
    lignoceric_acid_100g,
    cerotic_acid_100g,
    montanic_acid_100g,
    melissic_acid_100g,
    monounsaturated_fat_100g,
    polyunsaturated_fat_100g,
    omega_3_fat_100g,
    alpha_linolenic_acid_100g,
    eicosapentaenoic_acid_100g,
    docosahexaenoic_acid_100g,
    omega_6_fat_100g,
    linoleic_acid_100g,
    arachidonic_acid_100g,
    gamma_linolenic_acid_100g,
    dihomo_gamma_linolenic_acid_100g,
    omega_9_fat_100g,
    oleic_acid_100g,
    elaidic_acid_100g,
    gondoic_acid_100g,
    mead_acid_100g,
    erucic_acid_100g,
    nervonic_acid_100g,
    trans_fat_100g,
    cholesterol_100g,
    carbohydrates_100g,
    sugars_100g,
    sucrose_100g,
    glucose_100g,
    fructose_100g,
    lactose_100g,
    maltose_100g,
    maltodextrins_100g,
    starch_100g,
    polyols_100g,
    fiber_100g,
    proteins_100g,
    casein_100g,
    serum_proteins_100g,
    nucleotides_100g,
    salt_100g,
    sodium_100g,
    alcohol_100g,
    vitamin_a_100g,
    beta_carotene_100g,
    vitamin_d_100g,
    vitamin_e_100g,
    vitamin_k_100g,
    vitamin_c_100g,
    vitamin_b1_100g,
    vitamin_b2_100g,
    vitamin_pp_100g,
    vitamin_b6_100g,
    vitamin_b9_100g,
    vitamin_b12_100g,
    biotin_100g,
    pantothenic_acid_100g,
    silica_100g,
    bicarbonate_100g,
    potassium_100g,
    chloride_100g,
    calcium_100g,
    phosphorus_100g,
    iron_100g,
    magnesium_100g,
    zinc_100g,
    copper_100g,
    manganese_100g,
    fluoride_100g,
    selenium_100g,
    chromium_100g,
    molybdenum_100g,
    iodine_100g,
    caffeine_100g,
    taurine_100g,
    ph_100g,
    fruits_vegetables_nuts_100g,
    collagen_meat_protein_ratio_100g,
    cocoa_100g,
    chlorophyl_100g,
    carbon_footprint_100g,
    nutrition_score_fr_100g,
    nutrition_score_uk_100g
)
SELECT
    code::TEXT AS code,
    url::TEXT AS url,
    creator::TEXT AS creator,
    created_t::TEXT AS created_t,
    created_datetime::TEXT AS created_datetime,
    last_modified_t::TEXT AS last_modified_t,
    last_modified_datetime::TEXT AS last_modified_datetime,
    product_name::TEXT AS product_name,
    generic_name::TEXT AS generic_name,
    quantity::TEXT AS quantity,
    packaging::TEXT AS packaging,
    packaging_tags::TEXT AS packaging_tags,
    brands::TEXT AS brands,
    brands_tags::TEXT AS brands_tags,
    categories::TEXT AS categories,
    categories_tags::TEXT AS categories_tags,
    categories_en::TEXT AS categories_en,
    origins::TEXT AS origins,
    origins_tags::TEXT AS origins_tags,
    manufacturing_places::TEXT AS manufacturing_places,
    manufacturing_places_tags::TEXT AS manufacturing_places_tags,
    labels::TEXT AS labels,
    labels_tags::TEXT AS labels_tags,
    labels_en::TEXT AS labels_en,
    emb_codes::TEXT AS emb_codes,
    emb_codes_tags::TEXT AS emb_codes_tags,
    first_packaging_code_geo::TEXT AS first_packaging_code_geo,
    cities::TEXT AS cities,
    cities_tags::TEXT AS cities_tags,
    purchase_places::TEXT AS purchase_places,
    stores::TEXT AS stores,
    countries::TEXT AS countries,
    countries_tags::TEXT AS countries_tags,
    countries_en::TEXT AS countries_en,
    ingredients_text::TEXT AS ingredients_text,
    allergens::TEXT AS allergens,
    allergens_en::TEXT AS allergens_en,
    traces::TEXT AS traces,
    traces_tags::TEXT AS traces_tags,
    traces_en::TEXT AS traces_en,
    serving_size::TEXT AS serving_size,
    no_nutriments::NUMERIC AS no_nutriments,
    additives_n::NUMERIC AS additives_n,
    additives::TEXT AS additives,
    additives_tags::TEXT AS additives_tags,
    additives_en::TEXT AS additives_en,
    ingredients_from_palm_oil_n::NUMERIC AS ingredients_from_palm_oil_n,
    ingredients_from_palm_oil::NUMERIC AS ingredients_from_palm_oil,
    ingredients_from_palm_oil_tags::TEXT AS ingredients_from_palm_oil_tags,
    ingredients_that_may_be_from_palm_oil_n::NUMERIC AS ingredients_that_may_be_from_palm_oil_n,
    ingredients_that_may_be_from_palm_oil::NUMERIC AS ingredients_that_may_be_from_palm_oil,
    ingredients_that_may_be_from_palm_oil_tags::TEXT AS ingredients_that_may_be_from_palm_oil_tags,
    nutrition_grade_uk::NUMERIC AS nutrition_grade_uk,
    nutrition_grade_fr::TEXT AS nutrition_grade_fr,
    pnns_groups_1::TEXT AS pnns_groups_1,
    pnns_groups_2::TEXT AS pnns_groups_2,
    states::TEXT AS states,
    states_tags::TEXT AS states_tags,
    states_en::TEXT AS states_en,
    main_category::TEXT AS main_category,
    main_category_en::TEXT AS main_category_en,
    image_url::TEXT AS image_url,
    image_small_url::TEXT AS image_small_url,
    energy_100g::NUMERIC AS energy_100g,
    energy_from_fat_100g::NUMERIC AS energy_from_fat_100g,
    fat_100g::NUMERIC AS fat_100g,
    saturated_fat_100g::NUMERIC AS saturated_fat_100g,
    butyric_acid_100g::NUMERIC AS butyric_acid_100g,
    caproic_acid_100g::NUMERIC AS caproic_acid_100g,
    caprylic_acid_100g::NUMERIC AS caprylic_acid_100g,
    capric_acid_100g::NUMERIC AS capric_acid_100g,
    lauric_acid_100g::NUMERIC AS lauric_acid_100g,
    myristic_acid_100g::NUMERIC AS myristic_acid_100g,
    palmitic_acid_100g::NUMERIC AS palmitic_acid_100g,
    stearic_acid_100g::NUMERIC AS stearic_acid_100g,
    arachidic_acid_100g::NUMERIC AS arachidic_acid_100g,
    behenic_acid_100g::NUMERIC AS behenic_acid_100g,
    lignoceric_acid_100g::NUMERIC AS lignoceric_acid_100g,
    cerotic_acid_100g::NUMERIC AS cerotic_acid_100g,
    montanic_acid_100g::NUMERIC AS montanic_acid_100g,
    melissic_acid_100g::NUMERIC AS melissic_acid_100g,
    monounsaturated_fat_100g::NUMERIC AS monounsaturated_fat_100g,
    polyunsaturated_fat_100g::NUMERIC AS polyunsaturated_fat_100g,
    omega_3_fat_100g::NUMERIC AS omega_3_fat_100g,
    alpha_linolenic_acid_100g::NUMERIC AS alpha_linolenic_acid_100g,
    eicosapentaenoic_acid_100g::NUMERIC AS eicosapentaenoic_acid_100g,
    docosahexaenoic_acid_100g::NUMERIC AS docosahexaenoic_acid_100g,
    omega_6_fat_100g::NUMERIC AS omega_6_fat_100g,
    linoleic_acid_100g::NUMERIC AS linoleic_acid_100g,
    arachidonic_acid_100g::NUMERIC AS arachidonic_acid_100g,
    gamma_linolenic_acid_100g::NUMERIC AS gamma_linolenic_acid_100g,
    dihomo_gamma_linolenic_acid_100g::NUMERIC AS dihomo_gamma_linolenic_acid_100g,
    omega_9_fat_100g::NUMERIC AS omega_9_fat_100g,
    oleic_acid_100g::NUMERIC AS oleic_acid_100g,
    elaidic_acid_100g::NUMERIC AS elaidic_acid_100g,
    gondoic_acid_100g::NUMERIC AS gondoic_acid_100g,
    mead_acid_100g::NUMERIC AS mead_acid_100g,
    erucic_acid_100g::NUMERIC AS erucic_acid_100g,
    nervonic_acid_100g::NUMERIC AS nervonic_acid_100g,
    trans_fat_100g::NUMERIC AS trans_fat_100g,
    cholesterol_100g::NUMERIC AS cholesterol_100g,
    carbohydrates_100g::NUMERIC AS carbohydrates_100g,
    sugars_100g::NUMERIC AS sugars_100g,
    sucrose_100g::NUMERIC AS sucrose_100g,
    glucose_100g::NUMERIC AS glucose_100g,
    fructose_100g::NUMERIC AS fructose_100g,
    lactose_100g::NUMERIC AS lactose_100g,
    maltose_100g::NUMERIC AS maltose_100g,
    maltodextrins_100g::NUMERIC AS maltodextrins_100g,
    starch_100g::NUMERIC AS starch_100g,
    polyols_100g::NUMERIC AS polyols_100g,
    fiber_100g::NUMERIC AS fiber_100g,
    proteins_100g::NUMERIC AS proteins_100g,
    casein_100g::NUMERIC AS casein_100g,
    serum_proteins_100g::NUMERIC AS serum_proteins_100g,
    nucleotides_100g::NUMERIC AS nucleotides_100g,
    salt_100g::NUMERIC AS salt_100g,
    sodium_100g::NUMERIC AS sodium_100g,
    alcohol_100g::NUMERIC AS alcohol_100g,
    vitamin_a_100g::NUMERIC AS vitamin_a_100g,
    beta_carotene_100g::NUMERIC AS beta_carotene_100g,
    vitamin_d_100g::NUMERIC AS vitamin_d_100g,
    vitamin_e_100g::NUMERIC AS vitamin_e_100g,
    vitamin_k_100g::NUMERIC AS vitamin_k_100g,
    vitamin_c_100g::NUMERIC AS vitamin_c_100g,
    vitamin_b1_100g::NUMERIC AS vitamin_b1_100g,
    vitamin_b2_100g::NUMERIC AS vitamin_b2_100g,
    vitamin_pp_100g::NUMERIC AS vitamin_pp_100g,
    vitamin_b6_100g::NUMERIC AS vitamin_b6_100g,
    vitamin_b9_100g::NUMERIC AS vitamin_b9_100g,
    vitamin_b12_100g::NUMERIC AS vitamin_b12_100g,
    biotin_100g::NUMERIC AS biotin_100g,
    pantothenic_acid_100g::NUMERIC AS pantothenic_acid_100g,
    silica_100g::NUMERIC AS silica_100g,
    bicarbonate_100g::NUMERIC AS bicarbonate_100g,
    potassium_100g::NUMERIC AS potassium_100g,
    chloride_100g::NUMERIC AS chloride_100g,
    calcium_100g::NUMERIC AS calcium_100g,
    phosphorus_100g::NUMERIC AS phosphorus_100g,
    iron_100g::NUMERIC AS iron_100g,
    magnesium_100g::NUMERIC AS magnesium_100g,
    zinc_100g::NUMERIC AS zinc_100g,
    copper_100g::NUMERIC AS copper_100g,
    manganese_100g::NUMERIC AS manganese_100g,
    fluoride_100g::NUMERIC AS fluoride_100g,
    selenium_100g::NUMERIC AS selenium_100g,
    chromium_100g::NUMERIC AS chromium_100g,
    molybdenum_100g::NUMERIC AS molybdenum_100g,
    iodine_100g::NUMERIC AS iodine_100g,
    caffeine_100g::NUMERIC AS caffeine_100g,
    taurine_100g::NUMERIC AS taurine_100g,
    ph_100g::NUMERIC AS ph_100g,
    fruits_vegetables_nuts_100g::NUMERIC AS fruits_vegetables_nuts_100g,
    collagen_meat_protein_ratio_100g::NUMERIC AS collagen_meat_protein_ratio_100g,
    cocoa_100g::NUMERIC AS cocoa_100g,
    chlorophyl_100g::NUMERIC AS chlorophyl_100g,
    carbon_footprint_100g::NUMERIC AS carbon_footprint_100g,
    nutrition_score_fr_100g::NUMERIC AS nutrition_score_fr_100g,
    nutrition_score_uk_100g::NUMERIC AS nutrition_score_uk_100g
FROM raw_data;

-- Clean / Process the data
DELETE FROM foods WHERE product_name IS NULL and generic_name IS NULL;
UPDATE foods SET product_name = generic_name 
WHERE product_name IS NULL AND generic_name IS NOT NULL;

-- Cleanup product_name
UPDATE foods SET product_name = trim(both from product_name);
UPDATE foods SET product_name = lower(product_name);

-- Remove food with missing data
DELETE FROM foods WHERE energy_100g IS NULL
AND carbohydrates_100g IS NULL;

-- Remove french categories
UPDATE foods SET categories_en = NULL WHERE categories_en LIKE 'fr:%';
UPDATE foods SET categories_en = trim(both FROM categories_en);
UPDATE foods SET categories_en = lower(categories_en);


CREATE TABLE food_history
(
    food_history_id     SERIAL      NOT NULL PRIMARY KEY,
    user_id             INTEGER     REFERENCES users(user_id) NOT NULL,
    food_id             INTEGER     REFERENCES foods(food_id) NOT NULL,
    food_timestamp      TIMESTAMP   WITH TIME ZONE DEFAULT (now() AT TIME ZONE 'EST') NOT NULL,
    food_servings       NUMERIC     NOT NULL
);
